### ISSUE TITLE
Git tag latest release 1.3.8 & publish apk in github releases

### ISSUE THREAD

**Issue by emanuelb** [coingrig/coingrig-wallet#17]
latest release on google-play is: 1.3.8 https://play.google.com/store/apps/details?id=com.coingrig
while latest tag https://github.com/coingrig/coingrig-wallet/tags and release is 1.3.7 https://github.com/coingrig/coingrig-wallet/releases
tag the latest 1.3.8 release, and publish universal apk file of the release in github releases as asset as well.

**Comment by rvulpescu** [comment]
Thank you, we are tring to keep the code updated as soon as possible.
We will not be publishing at this moment the APK in github, but we are going to start publishing the APK on our official website soon.
