### ISSUE TITLE
An unexpected error occurred: "EACCES: permission denied, lstat 'dir:filepath\coingrig-wallet\\node_modules\\@coingrig\\wallet-generator\\ios\\CGWallet.xcframework\\ios-arm64_x86_64-simulator\\CGWallet.framework\\CGWallet

### ISSUE THREAD

**Issue by mkumail1** [coingrig/coingrig-wallet#21]
Hi I am trying to run this application using the command `yarn` on Windows but whenever I try to install dependencies I get this error: 

![image](https://user-images.githubusercontent.com/45015600/167485016-37fda98e-c1d3-4394-acbb-e06ca6dbba36.png)

I am using: 
Node: 14.17.0
Yarn: 1.22.5

**Comment by rvulpescu** [comment]
This is an issue from compiling on Windows, the symlinks used on MacOS do not replicate on Windows.
These do not affect compilation for Android on Windows and can be deleted to remove the error.
We'll update with an appropiate handling for Windows machines.
