### ISSUE TITLE
 Generic High Entropy Secret 

### ISSUE THREAD

**Issue by B3ns44d** [coingrig/coingrig-wallet#7]
A secret has been exposed in your git history.

file-path: https://github.com/coingrig/coingrig-wallet/commit/67c09484b296667a089a2425144c3870ef885d92#diff-2258fe64e0a333fde8c485f1813685fbdead1bd775f84afd3d6af2cafa11c071R25

```js
init = async () => {
    //@ts-ignore
    this.client = await WalletConnectClient.init({
      //   logger: 'debug',
      apiKey: '3c5......
```

**Comment by florindumitru** [comment]
@B3ns44d Thank you for notifying us, this is a key that is no longer valid, used during development.
